Add `links` to `package` section of Cargo.toml
Metaswitch/cassandra-sys-rs pull request #27
Opened 2020-02-19 13:16 UTC by yukim

I'm developing on windows so I'd like to customize link options to suite my env, using [overriding build script feature](https://doc.rust-lang.org/cargo/reference/build-scripts.html#overriding-build-scripts).

With this change, I can have my local Cargo config for linking cassandra driver like:

```
[target.x86_64-pc-windows-msvc.cassandra]
rustc-link-lib = ["..."]
```

2020-03-02 14:03 UTC, kw217 commented
Thanks. The docs you point at say
> When using the links key, the package must have a build script, and the build script should use the rustc-link-lib instruction to link the library.
Can you update `build.rs` to use this way of pulling in the library, rather than `cargo:rustc-flags=-l dylib=`? Or are the docs wrong here?

2020-03-03 22:53 UTC, yukim commented
I don't have changes for `build.rs` yet. I think what the doc suggest is to have "default" build script, which we already have for mac os and linux, and overwriting it for windows just works for me.
If you also want to have default windows build script in `build.rs`, I can work on that too.

2020-03-06 09:27 UTC, kw217 commented
Ah, I see. I suspect it's fine to just add the `links` key and make no further changes, though I'd be happy to accept the Windows build script as well if it's likely to work for others.

2020-03-06 09:27 UTC, kw217 approved these changes
LGTM - thanks.

2020-03-06 09:30 UTC, kw217 requested changes
Sorry, almost forgot - please can you update CHANGELOG?

2020-03-10 09:24 UTC, kw217 approved these changes
LGTM (really this time!)

2020-03-10 09:24 UTC, merged

2020-03-10 09:24 UTC, kw217 commented
Thanks @yukim !